-- Auto-generated courses seed
-- Generated at: 2025-08-29T16:46:52.609625Z
-- 
-- ENHANCED CURRICULUM - Lagos State Standards
-- Added missing subjects and improved course descriptions
-- 
-- NEW SUBJECTS ADDED:
-- - Rhymes & Poetry (KG2)
-- - Hausa, Yoruba, Igbo Languages (Primary)
-- - Islamic Religious Knowledge (JSS)
-- - Home Economics (JSS)
-- - Arabic Language (JSS)
-- - Local Languages (JSS)
-- - Technical Drawing (SS Science)
-- - Food & Nutrition (SS Science)
-- - Printing Technology (SS Trade)
-- - Photography (SS Trade)
-- - Additional Trade Subjects
--
-- IMPROVEMENTS:
-- - Enhanced course descriptions with learning objectives
-- - Added cultural and Nigerian context to subjects
-- - Included practical applications and skills development
-- - Added missing Lagos State curriculum subjects
BEGIN;

-- Drop the old courses table if it exists
DROP TABLE IF EXISTS public.courses;

-- Create a new, simple courses table without complex constraints
create table public.new_courses (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  class_level text not null,
  term text not null,
  category text not null,
  stream text,
  subject_type text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Upsert helper: use a CTE so we can bulk insert cleanly

with upsert as (
  select 1
)
insert into public.new_courses (name, code, description, class_level, term, category, stream) values
('Literacy', 'LIT021', 'Early literacy and phonics', 'KG1', '1st', 'Core', NULL),
('Numeracy', 'NUM021', 'Early numeracy and number sense', 'KG1', '1st', 'Core', NULL),
('Basic Science', 'BSC021', 'Introduction to the natural world', 'KG1', '1st', 'Core', NULL),
('Social Habits', 'SOH021', 'Civic and social habits for kids', 'KG1', '1st', 'Core', NULL),
('Creative Arts', 'ART021', 'Art, music, and crafts', 'KG1', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE021', 'Movement, games, and wellbeing', 'KG1', '1st', 'Core', NULL),
('Literacy', 'LIT022', 'Early literacy and phonics', 'KG1', '2nd', 'Core', NULL),
('Numeracy', 'NUM022', 'Early numeracy and number sense', 'KG1', '2nd', 'Core', NULL),
('Basic Science', 'BSC022', 'Introduction to the natural world', 'KG1', '2nd', 'Core', NULL),
('Social Habits', 'SOH022', 'Civic and social habits for kids', 'KG1', '2nd', 'Core', NULL),
('Creative Arts', 'ART022', 'Art, music, and crafts', 'KG1', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE022', 'Movement, games, and wellbeing', 'KG1', '2nd', 'Core', NULL),
('Literacy', 'LIT023', 'Early literacy and phonics', 'KG1', '3rd', 'Core', NULL),
('Numeracy', 'NUM023', 'Early numeracy and number sense', 'KG1', '3rd', 'Core', NULL),
('Basic Science', 'BSC023', 'Introduction to the natural world', 'KG1', '3rd', 'Core', NULL),
('Social Habits', 'SOH023', 'Civic and social habits for kids', 'KG1', '3rd', 'Core', NULL),
('Creative Arts', 'ART023', 'Art, music, and crafts', 'KG1', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE023', 'Movement, games, and wellbeing', 'KG1', '3rd', 'Core', NULL),

-- ================= KG2 COURSES (stream = NULL) =================
-- KG2 - 1st Term
('English', 'ENG024', 'English Language and Communication Skills - Developing listening, speaking, reading and writing abilities through interactive activities, stories, and songs', 'KG2', '1st', 'Core', NULL),
('Mathematics', 'MTH024', 'Basic Number Concepts and Counting - Introduction to numbers 1-50, basic shapes, patterns, and simple addition through hands-on activities and games', 'KG2', '1st', 'Core', NULL),
('Basic Science', 'BSC024', 'Introduction to the Natural World - Exploring living and non-living things, weather, seasons, and basic environmental awareness through observation and experiments', 'KG2', '1st', 'Core', NULL),
('Social Habits', 'SOH024', 'Civic and Social Habits for Kids - Developing good manners, respect for others, community awareness, and basic citizenship values through role-play and stories', 'KG2', '1st', 'Core', NULL),
('Creative Arts', 'ART024', 'Art, Music, and Crafts - Creative expression through drawing, painting, music, dance, and craft activities to develop imagination and motor skills', 'KG2', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE024', 'Movement, Games, and Wellbeing - Physical development through structured play, basic exercises, health awareness, and safety practices', 'KG2', '1st', 'Core', NULL),
('Rhymes & Poetry', 'RHY024', 'Rhymes, Poetry, and Language Development - Learning traditional and modern rhymes, poems, and songs to enhance language skills and cultural appreciation', 'KG2', '1st', 'Core', NULL),

-- KG2 - 2nd Term
('English', 'ENG025', 'English Language and Communication Skills', 'KG2', '2nd', 'Core', NULL),
('Mathematics', 'MTH025', 'Basic Number Concepts and Counting', 'KG2', '2nd', 'Core', NULL),
('Basic Science', 'BSC025', 'Introduction to the Natural World', 'KG2', '2nd', 'Core', NULL),
('Social Habits', 'SOH025', 'Civic and Social Habits for Kids', 'KG2', '2nd', 'Core', NULL),
('Creative Arts', 'ART025', 'Art, Music, and Crafts', 'KG2', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE025', 'Movement, Games, and Wellbeing', 'KG2', '2nd', 'Core', NULL),

-- KG2 - 3rd Term
('English', 'ENG026', 'English Language and Communication Skills', 'KG2', '3rd', 'Core', NULL),
('Mathematics', 'MTH026', 'Basic Number Concepts and Counting', 'KG2', '3rd', 'Core', NULL),
('Basic Science', 'BSC026', 'Introduction to the Natural World', 'KG2', '3rd', 'Core', NULL),
('Social Habits', 'SOH026', 'Civic and Social Habits for Kids', 'KG2', '3rd', 'Core', NULL),
('Creative Arts', 'ART026', 'Art, Music, and Crafts', 'KG2', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE026', 'Movement, Games, and Wellbeing', 'KG2', '3rd', 'Core', NULL),
('English', 'ENG311', 'English Language and Literature - Comprehensive development of reading, writing, speaking, and listening skills with focus on grammar, vocabulary, and comprehension', 'PRI1', '1st', 'Core', NULL),
('Mathematics', 'MTH311', 'Basic Mathematics and Number Work - Foundation in numbers, addition, subtraction, shapes, measurement, and problem-solving strategies', 'PRI1', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST311', 'Introduction to Science and Technology - Exploring the natural world, simple machines, technology in daily life, and basic scientific inquiry', 'PRI1', '1st', 'Core', NULL),
('Civic Education', 'CVE311', 'Basic Citizenship and Values - Understanding rights and responsibilities, community values, patriotism, and good character development', 'PRI1', '1st', 'Core', NULL),
('Agricultural Science', 'AGR311', 'Introduction to Agriculture - Basic farming practices, plant growth, animal care, and agricultural tools and their uses', 'PRI1', '1st', 'Core', NULL),
('Social Studies', 'SOS311', 'Basic Social Studies - Introduction to family, community, culture, geography, and historical events in Nigeria', 'PRI1', '1st', 'Core', NULL),
('Creative Arts', 'ART311', 'Creative Arts and Design - Visual arts, music, drama, and creative expression through various media and cultural activities', 'PRI1', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE311', 'Physical Education and Health - Physical fitness, sports skills, health awareness, nutrition, and safety education', 'PRI1', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER311', 'Verbal Reasoning Skills - Critical thinking, logical reasoning, vocabulary development, and problem-solving through language', 'PRI1', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR311', 'Quantitative Reasoning Skills - Mathematical thinking, pattern recognition, logical reasoning, and analytical problem-solving', 'PRI1', '1st', 'Core', NULL),
('Hausa Language', 'HAU311', 'Hausa Language and Culture - Introduction to Hausa language, basic communication, cultural practices, and traditions', 'PRI1', '1st', 'Core', NULL),
('Yoruba Language', 'YOR311', 'Yoruba Language and Culture - Introduction to Yoruba language, basic communication, cultural practices, and traditions', 'PRI1', '1st', 'Core', NULL),
('Igbo Language', 'IGB311', 'Igbo Language and Culture - Introduction to Igbo language, basic communication, cultural practices, and traditions', 'PRI1', '1st', 'Core', NULL),
('English', 'ENG312', 'English Language and Literature', 'PRI1', '2nd', 'Core', NULL),
('Mathematics', 'MTH312', 'Basic Mathematics and Number Work', 'PRI1', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST312', 'Introduction to Science and Technology', 'PRI1', '2nd', 'Core', NULL),
('Civic Education', 'CVE312', 'Basic Citizenship and Values', 'PRI1', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR312', 'Introduction to Agriculture', 'PRI1', '2nd', 'Core', NULL),
('Social Studies', 'SOS312', 'Basic Social Studies', 'PRI1', '2nd', 'Core', NULL),
('Creative Arts', 'ART312', 'Creative Arts and Design', 'PRI1', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE312', 'Physical Education and Health', 'PRI1', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER312', 'Verbal Reasoning Skills', 'PRI1', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR312', 'Quantitative Reasoning Skills', 'PRI1', '2nd', 'Core', NULL),
('English', 'ENG313', 'English Language and Literature', 'PRI1', '3rd', 'Core', NULL),
('Mathematics', 'MTH313', 'Basic Mathematics and Number Work', 'PRI1', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST313', 'Introduction to Science and Technology', 'PRI1', '3rd', 'Core', NULL),
('Civic Education', 'CVE313', 'Basic Citizenship and Values', 'PRI1', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR313', 'Introduction to Agriculture', 'PRI1', '3rd', 'Core', NULL),
('Social Studies', 'SOS313', 'Basic Social Studies', 'PRI1', '3rd', 'Core', NULL),
('Creative Arts', 'ART313', 'Creative Arts and Design', 'PRI1', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE313', 'Physical Education and Health', 'PRI1', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER313', 'Verbal Reasoning Skills', 'PRI1', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR313', 'Quantitative Reasoning Skills', 'PRI1', '3rd', 'Core', NULL),
('English', 'ENG321', 'English Language and Literature', 'PRI2', '1st', 'Core', NULL),
('Mathematics', 'MTH321', 'Basic Mathematics and Number Work', 'PRI2', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST321', 'Introduction to Science and Technology', 'PRI2', '1st', 'Core', NULL),
('Civic Education', 'CVE321', 'Basic Citizenship and Values', 'PRI2', '1st', 'Core', NULL),
('Agricultural Science', 'AGR321', 'Introduction to Agriculture', 'PRI2', '1st', 'Core', NULL),
('Social Studies', 'SOS321', 'Basic Social Studies', 'PRI2', '1st', 'Core', NULL),
('Creative Arts', 'ART321', 'Creative Arts and Design', 'PRI2', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE321', 'Physical Education and Health', 'PRI2', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER321', 'Verbal Reasoning Skills', 'PRI2', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR321', 'Quantitative Reasoning Skills', 'PRI2', '1st', 'Core', NULL),
('English', 'ENG322', 'English Language and Literature', 'PRI2', '2nd', 'Core', NULL),
('Mathematics', 'MTH322', 'Basic Mathematics and Number Work', 'PRI2', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST322', 'Introduction to Science and Technology', 'PRI2', '2nd', 'Core', NULL),
('Civic Education', 'CVE322', 'Basic Citizenship and Values', 'PRI2', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR322', 'Introduction to Agriculture', 'PRI2', '2nd', 'Core', NULL),
('Social Studies', 'SOS322', 'Basic Social Studies', 'PRI2', '2nd', 'Core', NULL),
('Creative Arts', 'ART322', 'Creative Arts and Design', 'PRI2', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE322', 'Physical Education and Health', 'PRI2', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER322', 'Verbal Reasoning Skills', 'PRI2', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR322', 'Quantitative Reasoning Skills', 'PRI2', '2nd', 'Core', NULL),
('English', 'ENG323', 'English Language and Literature', 'PRI2', '3rd', 'Core', NULL),
('Mathematics', 'MTH323', 'Basic Mathematics and Number Work', 'PRI2', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST323', 'Introduction to Science and Technology', 'PRI2', '3rd', 'Core', NULL),
('Civic Education', 'CVE323', 'Basic Citizenship and Values', 'PRI2', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR323', 'Introduction to Agriculture', 'PRI2', '3rd', 'Core', NULL),
('Social Studies', 'SOS323', 'Basic Social Studies', 'PRI2', '3rd', 'Core', NULL),
('Creative Arts', 'ART323', 'Creative Arts and Design', 'PRI2', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE323', 'Physical Education and Health', 'PRI2', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER323', 'Verbal Reasoning Skills', 'PRI2', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR323', 'Quantitative Reasoning Skills', 'PRI2', '3rd', 'Core', NULL),
('English', 'ENG331', 'English Language and Literature', 'PRI3', '1st', 'Core', NULL),
('Mathematics', 'MTH331', 'Basic Mathematics and Number Work', 'PRI3', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST331', 'Introduction to Science and Technology', 'PRI3', '1st', 'Core', NULL),
('Civic Education', 'CVE331', 'Basic Citizenship and Values', 'PRI3', '1st', 'Core', NULL),
('Agricultural Science', 'AGR331', 'Introduction to Agriculture', 'PRI3', '1st', 'Core', NULL),
('Social Studies', 'SOS331', 'Basic Social Studies', 'PRI3', '1st', 'Core', NULL),
('Creative Arts', 'ART331', 'Creative Arts and Design', 'PRI3', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE331', 'Physical Education and Health', 'PRI3', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER331', 'Verbal Reasoning Skills', 'PRI3', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR331', 'Quantitative Reasoning Skills', 'PRI3', '1st', 'Core', NULL),
('English', 'ENG332', 'English Language and Literature', 'PRI3', '2nd', 'Core', NULL),
('Mathematics', 'MTH332', 'Basic Mathematics and Number Work', 'PRI3', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST332', 'Introduction to Science and Technology', 'PRI3', '2nd', 'Core', NULL),
('Civic Education', 'CVE332', 'Basic Citizenship and Values', 'PRI3', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR332', 'Introduction to Agriculture', 'PRI3', '2nd', 'Core', NULL),
('Social Studies', 'SOS332', 'Basic Social Studies', 'PRI3', '2nd', 'Core', NULL),
('Creative Arts', 'ART332', 'Creative Arts and Design', 'PRI3', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE332', 'Physical Education and Health', 'PRI3', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER332', 'Verbal Reasoning Skills', 'PRI3', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR332', 'Quantitative Reasoning Skills', 'PRI3', '2nd', 'Core', NULL),
('English', 'ENG333', 'English Language and Literature', 'PRI3', '3rd', 'Core', NULL),
('Mathematics', 'MTH333', 'Basic Mathematics and Number Work', 'PRI3', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST333', 'Introduction to Science and Technology', 'PRI3', '3rd', 'Core', NULL),
('Civic Education', 'CVE333', 'Basic Citizenship and Values', 'PRI3', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR333', 'Introduction to Agriculture', 'PRI3', '3rd', 'Core', NULL),
('Social Studies', 'SOS333', 'Basic Social Studies', 'PRI3', '3rd', 'Core', NULL),
('Creative Arts', 'ART333', 'Creative Arts and Design', 'PRI3', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE333', 'Physical Education and Health', 'PRI3', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER333', 'Verbal Reasoning Skills', 'PRI3', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR333', 'Quantitative Reasoning Skills', 'PRI3', '3rd', 'Core', NULL),
('English', 'ENG341', 'English Language and Literature', 'PRI4', '1st', 'Core', NULL),
('Mathematics', 'MTH341', 'Basic Mathematics and Number Work', 'PRI4', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST341', 'Introduction to Science and Technology', 'PRI4', '1st', 'Core', NULL),
('Civic Education', 'CVE341', 'Basic Citizenship and Values', 'PRI4', '1st', 'Core', NULL),
('Agricultural Science', 'AGR341', 'Introduction to Agriculture', 'PRI4', '1st', 'Core', NULL),
('Social Studies', 'SOS341', 'Basic Social Studies', 'PRI4', '1st', 'Core', NULL),
('Creative Arts', 'ART341', 'Creative Arts and Design', 'PRI4', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE341', 'Physical Education and Health', 'PRI4', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER341', 'Verbal Reasoning Skills', 'PRI4', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR341', 'Quantitative Reasoning Skills', 'PRI4', '1st', 'Core', NULL),
('English', 'ENG342', 'English Language and Literature', 'PRI4', '2nd', 'Core', NULL),
('Mathematics', 'MTH342', 'Basic Mathematics and Number Work', 'PRI4', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST342', 'Introduction to Science and Technology', 'PRI4', '2nd', 'Core', NULL),
('Civic Education', 'CVE342', 'Basic Citizenship and Values', 'PRI4', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR342', 'Introduction to Agriculture', 'PRI4', '2nd', 'Core', NULL),
('Social Studies', 'SOS342', 'Basic Social Studies', 'PRI4', '2nd', 'Core', NULL),
('Creative Arts', 'ART342', 'Creative Arts and Design', 'PRI4', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE342', 'Physical Education and Health', 'PRI4', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER342', 'Verbal Reasoning Skills', 'PRI4', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR342', 'Quantitative Reasoning Skills', 'PRI4', '2nd', 'Core', NULL),
('English', 'ENG343', 'English Language and Literature', 'PRI4', '3rd', 'Core', NULL),
('Mathematics', 'MTH343', 'Basic Mathematics and Number Work', 'PRI4', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST343', 'Introduction to Science and Technology', 'PRI4', '3rd', 'Core', NULL),
('Civic Education', 'CVE343', 'Basic Citizenship and Values', 'PRI4', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR343', 'Introduction to Agriculture', 'PRI4', '3rd', 'Core', NULL),
('Social Studies', 'SOS343', 'Basic Social Studies', 'PRI4', '3rd', 'Core', NULL),
('Creative Arts', 'ART343', 'Creative Arts and Design', 'PRI4', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE343', 'Physical Education and Health', 'PRI4', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER343', 'Verbal Reasoning Skills', 'PRI4', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR343', 'Quantitative Reasoning Skills', 'PRI4', '3rd', 'Core', NULL),
('English', 'ENG351', 'English Language and Literature', 'PRI5', '1st', 'Core', NULL),
('Mathematics', 'MTH351', 'Basic Mathematics and Number Work', 'PRI5', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST351', 'Introduction to Science and Technology', 'PRI5', '1st', 'Core', NULL),
('Civic Education', 'CVE351', 'Basic Citizenship and Values', 'PRI5', '1st', 'Core', NULL),
('Agricultural Science', 'AGR351', 'Introduction to Agriculture', 'PRI5', '1st', 'Core', NULL),
('Social Studies', 'SOS351', 'Basic Social Studies', 'PRI5', '1st', 'Core', NULL),
('Creative Arts', 'ART351', 'Creative Arts and Design', 'PRI5', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE351', 'Physical Education and Health', 'PRI5', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER351', 'Verbal Reasoning Skills', 'PRI5', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR351', 'Quantitative Reasoning Skills', 'PRI5', '1st', 'Core', NULL),
('English', 'ENG352', 'English Language and Literature', 'PRI5', '2nd', 'Core', NULL),
('Mathematics', 'MTH352', 'Basic Mathematics and Number Work', 'PRI5', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST352', 'Introduction to Science and Technology', 'PRI5', '2nd', 'Core', NULL),
('Civic Education', 'CVE352', 'Basic Citizenship and Values', 'PRI5', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR352', 'Introduction to Agriculture', 'PRI5', '2nd', 'Core', NULL),
('Social Studies', 'SOS352', 'Basic Social Studies', 'PRI5', '2nd', 'Core', NULL),
('Creative Arts', 'ART352', 'Creative Arts and Design', 'PRI5', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE352', 'Physical Education and Health', 'PRI5', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER352', 'Verbal Reasoning Skills', 'PRI5', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR352', 'Quantitative Reasoning Skills', 'PRI5', '2nd', 'Core', NULL),
('English', 'ENG353', 'English Language and Literature', 'PRI5', '3rd', 'Core', NULL),
('Mathematics', 'MTH353', 'Basic Mathematics and Number Work', 'PRI5', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST353', 'Introduction to Science and Technology', 'PRI5', '3rd', 'Core', NULL),
('Civic Education', 'CVE353', 'Basic Citizenship and Values', 'PRI5', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR353', 'Introduction to Agriculture', 'PRI5', '3rd', 'Core', NULL),
('Social Studies', 'SOS353', 'Basic Social Studies', 'PRI5', '3rd', 'Core', NULL),
('Creative Arts', 'ART353', 'Creative Arts and Design', 'PRI5', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE353', 'Physical Education and Health', 'PRI5', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER353', 'Verbal Reasoning Skills', 'PRI5', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR353', 'Quantitative Reasoning Skills', 'PRI5', '3rd', 'Core', NULL),
('English', 'ENG361', 'English Language and Literature', 'PRI6', '1st', 'Core', NULL),
('Mathematics', 'MTH361', 'Basic Mathematics and Number Work', 'PRI6', '1st', 'Core', NULL),
('Basic Science & Technology', 'BST361', 'Introduction to Science and Technology', 'PRI6', '1st', 'Core', NULL),
('Civic Education', 'CVE361', 'Basic Citizenship and Values', 'PRI6', '1st', 'Core', NULL),
('Agricultural Science', 'AGR361', 'Introduction to Agriculture', 'PRI6', '1st', 'Core', NULL),
('Social Studies', 'SOS361', 'Basic Social Studies', 'PRI6', '1st', 'Core', NULL),
('Creative Arts', 'ART361', 'Creative Arts and Design', 'PRI6', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE361', 'Physical Education and Health', 'PRI6', '1st', 'Core', NULL),
('Verbal Reasoning', 'VER361', 'Verbal Reasoning Skills', 'PRI6', '1st', 'Core', NULL),
('Quantitative Reasoning', 'QTR361', 'Quantitative Reasoning Skills', 'PRI6', '1st', 'Core', NULL),
('English', 'ENG362', 'English Language and Literature', 'PRI6', '2nd', 'Core', NULL),
('Mathematics', 'MTH362', 'Basic Mathematics and Number Work', 'PRI6', '2nd', 'Core', NULL),
('Basic Science & Technology', 'BST362', 'Introduction to Science and Technology', 'PRI6', '2nd', 'Core', NULL),
('Civic Education', 'CVE362', 'Basic Citizenship and Values', 'PRI6', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR362', 'Introduction to Agriculture', 'PRI6', '2nd', 'Core', NULL),
('Social Studies', 'SOS362', 'Basic Social Studies', 'PRI6', '2nd', 'Core', NULL),
('Creative Arts', 'ART362', 'Creative Arts and Design', 'PRI6', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE362', 'Physical Education and Health', 'PRI6', '2nd', 'Core', NULL),
('Verbal Reasoning', 'VER362', 'Verbal Reasoning Skills', 'PRI6', '2nd', 'Core', NULL),
('Quantitative Reasoning', 'QTR362', 'Quantitative Reasoning Skills', 'PRI6', '2nd', 'Core', NULL),
('English', 'ENG363', 'English Language and Literature', 'PRI6', '3rd', 'Core', NULL),
('Mathematics', 'MTH363', 'Basic Mathematics and Number Work', 'PRI6', '3rd', 'Core', NULL),
('Basic Science & Technology', 'BST363', 'Introduction to Science and Technology', 'PRI6', '3rd', 'Core', NULL),
('Civic Education', 'CVE363', 'Basic Citizenship and Values', 'PRI6', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR363', 'Introduction to Agriculture', 'PRI6', '3rd', 'Core', NULL),
('Social Studies', 'SOS363', 'Basic Social Studies', 'PRI6', '3rd', 'Core', NULL),
('Creative Arts', 'ART363', 'Creative Arts and Design', 'PRI6', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE363', 'Physical Education and Health', 'PRI6', '3rd', 'Core', NULL),
('Verbal Reasoning', 'VER363', 'Verbal Reasoning Skills', 'PRI6', '3rd', 'Core', NULL),
('Quantitative Reasoning', 'QTR363', 'Quantitative Reasoning Skills', 'PRI6', '3rd', 'Core', NULL),
('English', 'ENG111', 'English Language and Literature - Advanced grammar, composition, literature appreciation, and communication skills development', 'JSS1', '1st', 'Core', NULL),
('Mathematics', 'MTH111', 'Basic Mathematics - Algebra, geometry, statistics, and mathematical reasoning with real-world applications', 'JSS1', '1st', 'Core', NULL),
('Basic Science', 'BSC111', 'Basic Science - Integrated study of physics, chemistry, and biology with practical experiments and scientific method', 'JSS1', '1st', 'Core', NULL),
('Basic Technology', 'BTE111', 'Basic Technology - Introduction to technical drawing, woodwork, metalwork, and basic engineering principles', 'JSS1', '1st', 'Core', NULL),
('Social Studies', 'SOS111', 'Social Studies - Nigerian history, geography, government, and social issues with critical analysis', 'JSS1', '1st', 'Core', NULL),
('Civic Education', 'CVE111', 'Civic Education - Citizenship, democracy, human rights, and civic responsibilities in Nigerian society', 'JSS1', '1st', 'Core', NULL),
('Computer Studies', 'ICT111', 'Computer Studies - Computer fundamentals, word processing, spreadsheets, and basic programming concepts', 'JSS1', '1st', 'Core', NULL),
('Agricultural Science', 'AGR111', 'Agricultural Science - Crop production, animal husbandry, soil science, and agricultural economics', 'JSS1', '1st', 'Core', NULL),
('Creative Arts', 'ART111', 'Creative Arts - Visual arts, music, drama, and cultural expression with Nigerian artistic traditions', 'JSS1', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE111', 'Physical & Health Education - Sports, fitness, health education, and personal development through physical activities', 'JSS1', '1st', 'Core', NULL),
('French', 'FRN111', 'French Language - Basic French communication, grammar, vocabulary, and cultural understanding', 'JSS1', '1st', 'Core', NULL),
('Business Studies', 'BUS111', 'Business Studies - Introduction to business concepts, entrepreneurship, and economic principles', 'JSS1', '1st', 'Core', NULL),
('Religious Studies', 'CRK111', 'Christian Religious Knowledge - Biblical studies, Christian ethics, and moral development', 'JSS1', '1st', 'Core', NULL),
('Islamic Religious Knowledge', 'IRK111', 'Islamic Religious Knowledge - Quranic studies, Islamic ethics, and moral development', 'JSS1', '1st', 'Core', NULL),
('Home Economics', 'HEC111', 'Home Economics - Family life, nutrition, clothing, and home management skills', 'JSS1', '1st', 'Core', NULL),
('Arabic Language', 'ARB111', 'Arabic Language - Basic Arabic communication, grammar, and Islamic cultural context', 'JSS1', '1st', 'Core', NULL),
('Local Languages', 'LOC111', 'Local Languages - Study of Nigerian indigenous languages and cultural heritage', 'JSS1', '1st', 'Core', NULL),
('English', 'ENG112', 'English Language and Literature', 'JSS1', '2nd', 'Core', NULL),
('Mathematics', 'MTH112', 'Basic Mathematics', 'JSS1', '2nd', 'Core', NULL),
('Basic Science', 'BSC112', 'Basic Science', 'JSS1', '2nd', 'Core', NULL),
('Basic Technology', 'BTE112', 'Basic Technology', 'JSS1', '2nd', 'Core', NULL),
('Social Studies', 'SOS112', 'Social Studies', 'JSS1', '2nd', 'Core', NULL),
('Civic Education', 'CVE112', 'Civic Education', 'JSS1', '2nd', 'Core', NULL),
('Computer Studies', 'ICT112', 'Computer Studies', 'JSS1', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR112', 'Agricultural Science', 'JSS1', '2nd', 'Core', NULL),
('Creative Arts', 'ART112', 'Creative Arts', 'JSS1', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE112', 'Physical & Health Education', 'JSS1', '2nd', 'Core', NULL),
('French', 'FRN112', 'French Language', 'JSS1', '2nd', 'Core', NULL),
('Business Studies', 'BUS112', 'Business Studies', 'JSS1', '2nd', 'Core', NULL),
('Religious Studies', 'CRK112', 'Christian Religious Knowledge', 'JSS1', '2nd', 'Core', NULL),
('English', 'ENG113', 'English Language and Literature', 'JSS1', '3rd', 'Core', NULL),
('Mathematics', 'MTH113', 'Basic Mathematics', 'JSS1', '3rd', 'Core', NULL),
('Basic Science', 'BSC113', 'Basic Science', 'JSS1', '3rd', 'Core', NULL),
('Basic Technology', 'BTE113', 'Basic Technology', 'JSS1', '3rd', 'Core', NULL),
('Social Studies', 'SOS113', 'Social Studies', 'JSS1', '3rd', 'Core', NULL),
('Civic Education', 'CVE113', 'Civic Education', 'JSS1', '3rd', 'Core', NULL),
('Computer Studies', 'ICT113', 'Computer Studies', 'JSS1', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR113', 'Agricultural Science', 'JSS1', '3rd', 'Core', NULL),
('Creative Arts', 'ART113', 'Creative Arts', 'JSS1', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE113', 'Physical & Health Education', 'JSS1', '3rd', 'Core', NULL),
('French', 'FRN113', 'French Language', 'JSS1', '3rd', 'Core', NULL),
('Business Studies', 'BUS113', 'Business Studies', 'JSS1', '3rd', 'Core', NULL),
('Religious Studies', 'CRK113', 'Christian Religious Knowledge', 'JSS1', '3rd', 'Core', NULL),
('English', 'ENG121', 'English Language and Literature', 'JSS2', '1st', 'Core', NULL),
('Mathematics', 'MTH121', 'Basic Mathematics', 'JSS2', '1st', 'Core', NULL),
('Basic Science', 'BSC121', 'Basic Science', 'JSS2', '1st', 'Core', NULL),
('Basic Technology', 'BTE121', 'Basic Technology', 'JSS2', '1st', 'Core', NULL),
('Social Studies', 'SOS121', 'Social Studies', 'JSS2', '1st', 'Core', NULL),
('Civic Education', 'CVE121', 'Civic Education', 'JSS2', '1st', 'Core', NULL),
('Computer Studies', 'ICT121', 'Computer Studies', 'JSS2', '1st', 'Core', NULL),
('Agricultural Science', 'AGR121', 'Agricultural Science', 'JSS2', '1st', 'Core', NULL),
('Creative Arts', 'ART121', 'Creative Arts', 'JSS2', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE121', 'Physical & Health Education', 'JSS2', '1st', 'Core', NULL),
('French', 'FRN121', 'French Language', 'JSS2', '1st', 'Core', NULL),
('Business Studies', 'BUS121', 'Business Studies', 'JSS2', '1st', 'Core', NULL),
('Religious Studies', 'CRK121', 'Christian Religious Knowledge', 'JSS2', '1st', 'Core', NULL),
('English', 'ENG122', 'English Language and Literature', 'JSS2', '2nd', 'Core', NULL),
('Mathematics', 'MTH122', 'Basic Mathematics', 'JSS2', '2nd', 'Core', NULL),
('Basic Science', 'BSC122', 'Basic Science', 'JSS2', '2nd', 'Core', NULL),
('Basic Technology', 'BTE122', 'Basic Technology', 'JSS2', '2nd', 'Core', NULL),
('Social Studies', 'SOS122', 'Social Studies', 'JSS2', '2nd', 'Core', NULL),
('Civic Education', 'CVE122', 'Civic Education', 'JSS2', '2nd', 'Core', NULL),
('Computer Studies', 'ICT122', 'Computer Studies', 'JSS2', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR122', 'Agricultural Science', 'JSS2', '2nd', 'Core', NULL),
('Creative Arts', 'ART122', 'Creative Arts', 'JSS2', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE122', 'Physical & Health Education', 'JSS2', '2nd', 'Core', NULL),
('French', 'FRN122', 'French Language', 'JSS2', '2nd', 'Core', NULL),
('Business Studies', 'BUS122', 'Business Studies', 'JSS2', '2nd', 'Core', NULL),
('Religious Studies', 'CRK122', 'Christian Religious Knowledge', 'JSS2', '2nd', 'Core', NULL),
('English', 'ENG123', 'English Language and Literature', 'JSS2', '3rd', 'Core', NULL),
('Mathematics', 'MTH123', 'Basic Mathematics', 'JSS2', '3rd', 'Core', NULL),
('Basic Science', 'BSC123', 'Basic Science', 'JSS2', '3rd', 'Core', NULL),
('Basic Technology', 'BTE123', 'Basic Technology', 'JSS2', '3rd', 'Core', NULL),
('Social Studies', 'SOS123', 'Social Studies', 'JSS2', '3rd', 'Core', NULL),
('Civic Education', 'CVE123', 'Civic Education', 'JSS2', '3rd', 'Core', NULL),
('Computer Studies', 'ICT123', 'Computer Studies', 'JSS2', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR123', 'Agricultural Science', 'JSS2', '3rd', 'Core', NULL),
('Creative Arts', 'ART123', 'Creative Arts', 'JSS2', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE123', 'Physical & Health Education', 'JSS2', '3rd', 'Core', NULL),
('French', 'FRN123', 'French Language', 'JSS2', '3rd', 'Core', NULL),
('Business Studies', 'BUS123', 'Business Studies', 'JSS2', '3rd', 'Core', NULL),
('Religious Studies', 'CRK123', 'Christian Religious Knowledge', 'JSS2', '3rd', 'Core', NULL),
('English', 'ENG131', 'English Language and Literature', 'JSS3', '1st', 'Core', NULL),
('Mathematics', 'MTH131', 'Basic Mathematics', 'JSS3', '1st', 'Core', NULL),
('Basic Science', 'BSC131', 'Basic Science', 'JSS3', '1st', 'Core', NULL),
('Basic Technology', 'BTE131', 'Basic Technology', 'JSS3', '1st', 'Core', NULL),
('Social Studies', 'SOS131', 'Social Studies', 'JSS3', '1st', 'Core', NULL),
('Civic Education', 'CVE131', 'Civic Education', 'JSS3', '1st', 'Core', NULL),
('Computer Studies', 'ICT131', 'Computer Studies', 'JSS3', '1st', 'Core', NULL),
('Agricultural Science', 'AGR131', 'Agricultural Science', 'JSS3', '1st', 'Core', NULL),
('Creative Arts', 'ART131', 'Creative Arts', 'JSS3', '1st', 'Core', NULL),
('Physical & Health Education', 'PHE131', 'Physical & Health Education', 'JSS3', '1st', 'Core', NULL),
('French', 'FRN131', 'French Language', 'JSS3', '1st', 'Core', NULL),
('Business Studies', 'BUS131', 'Business Studies', 'JSS3', '1st', 'Core', NULL),
('Religious Studies', 'CRK131', 'Christian Religious Knowledge', 'JSS3', '1st', 'Core', NULL),
('English', 'ENG132', 'English Language and Literature', 'JSS3', '2nd', 'Core', NULL),
('Mathematics', 'MTH132', 'Basic Mathematics', 'JSS3', '2nd', 'Core', NULL),
('Basic Science', 'BSC132', 'Basic Science', 'JSS3', '2nd', 'Core', NULL),
('Basic Technology', 'BTE132', 'Basic Technology', 'JSS3', '2nd', 'Core', NULL),
('Social Studies', 'SOS132', 'Social Studies', 'JSS3', '2nd', 'Core', NULL),
('Civic Education', 'CVE132', 'Civic Education', 'JSS3', '2nd', 'Core', NULL),
('Computer Studies', 'ICT132', 'Computer Studies', 'JSS3', '2nd', 'Core', NULL),
('Agricultural Science', 'AGR132', 'Agricultural Science', 'JSS3', '2nd', 'Core', NULL),
('Creative Arts', 'ART132', 'Creative Arts', 'JSS3', '2nd', 'Core', NULL),
('Physical & Health Education', 'PHE132', 'Physical & Health Education', 'JSS3', '2nd', 'Core', NULL),
('French', 'FRN132', 'French Language', 'JSS3', '2nd', 'Core', NULL),
('Business Studies', 'BUS132', 'Business Studies', 'JSS3', '2nd', 'Core', NULL),
('Religious Studies', 'CRK132', 'Christian Religious Knowledge', 'JSS3', '2nd', 'Core', NULL),
('English', 'ENG133', 'English Language and Literature', 'JSS3', '3rd', 'Core', NULL),
('Mathematics', 'MTH133', 'Basic Mathematics', 'JSS3', '3rd', 'Core', NULL),
('Basic Science', 'BSC133', 'Basic Science', 'JSS3', '3rd', 'Core', NULL),
('Basic Technology', 'BTE133', 'Basic Technology', 'JSS3', '3rd', 'Core', NULL),
('Social Studies', 'SOS133', 'Social Studies', 'JSS3', '3rd', 'Core', NULL),
('Civic Education', 'CVE133', 'Civic Education', 'JSS3', '3rd', 'Core', NULL),
('Computer Studies', 'ICT133', 'Computer Studies', 'JSS3', '3rd', 'Core', NULL),
('Agricultural Science', 'AGR133', 'Agricultural Science', 'JSS3', '3rd', 'Core', NULL),
('Creative Arts', 'ART133', 'Creative Arts', 'JSS3', '3rd', 'Core', NULL),
('Physical & Health Education', 'PHE133', 'Physical & Health Education', 'JSS3', '3rd', 'Core', NULL),
('French', 'FRN133', 'French Language', 'JSS3', '3rd', 'Core', NULL),
('Business Studies', 'BUS133', 'Business Studies', 'JSS3', '3rd', 'Core', NULL),
('Religious Studies', 'CRK133', 'Christian Religious Knowledge', 'JSS3', '3rd', 'Core', NULL),
('English', 'ENG211', 'English Language and Literature', 'SS1', '1st', 'Core', 'Science'),
('Mathematics', 'MTH211', 'Mathematics', 'SS1', '1st', 'Core', 'Science'),
('Biology', 'BIO211', 'Biology', 'SS1', '1st', 'Core', 'Science'),
('Chemistry', 'CHM211', 'Chemistry', 'SS1', '1st', 'Core', 'Science'),
('Physics', 'PHY211', 'Physics', 'SS1', '1st', 'Core', 'Science'),
('Further Mathematics', 'FMH211', 'Further Mathematics', 'SS1', '1st', 'Elective', 'Science'),
('Agricultural Science', 'AGR211', 'Agricultural Science', 'SS1', '1st', 'Core', 'Science'),
('Economics', 'ECO211', 'Economics', 'SS1', '1st', 'Core', 'Science'),
('Civic Education', 'CVE211', 'Civic Education', 'SS1', '1st', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT211', 'Information and Communication Technology', 'SS1', '1st', 'Core', 'Science'),
('English', 'ENG212', 'English Language and Literature', 'SS1', '2nd', 'Core', 'Science'),
('Mathematics', 'MTH212', 'Mathematics', 'SS1', '2nd', 'Core', 'Science'),
('Biology', 'BIO212', 'Biology', 'SS1', '2nd', 'Core', 'Science'),
('Chemistry', 'CHM212', 'Chemistry', 'SS1', '2nd', 'Core', 'Science'),
('Physics', 'PHY212', 'Physics', 'SS1', '2nd', 'Core', 'Science'),
('Further Mathematics', 'FMH212', 'Further Mathematics', 'SS1', '2nd', 'Elective', 'Science'),
('Agricultural Science', 'AGR212', 'Agricultural Science', 'SS1', '2nd', 'Core', 'Science'),
('Economics', 'ECO212', 'Economics', 'SS1', '2nd', 'Core', 'Science'),
('Civic Education', 'CVE212', 'Civic Education', 'SS1', '2nd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT212', 'Information and Communication Technology', 'SS1', '2nd', 'Core', 'Science'),
('English', 'ENG213', 'English Language and Literature', 'SS1', '3rd', 'Core', 'Science'),
('Mathematics', 'MTH213', 'Mathematics', 'SS1', '3rd', 'Core', 'Science'),
('Biology', 'BIO213', 'Biology', 'SS1', '3rd', 'Core', 'Science'),
('Chemistry', 'CHM213', 'Chemistry', 'SS1', '3rd', 'Core', 'Science'),
('Physics', 'PHY213', 'Physics', 'SS1', '3rd', 'Core', 'Science'),
('Further Mathematics', 'FMH213', 'Further Mathematics', 'SS1', '3rd', 'Elective', 'Science'),
('Agricultural Science', 'AGR213', 'Agricultural Science', 'SS1', '3rd', 'Core', 'Science'),
('Economics', 'ECO213', 'Economics', 'SS1', '3rd', 'Core', 'Science'),
('Civic Education', 'CVE213', 'Civic Education', 'SS1', '3rd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT213', 'Information and Communication Technology', 'SS1', '3rd', 'Core', 'Science'),
('English', 'ENG221', 'English Language and Literature - Advanced literary analysis, composition, and communication skills for academic excellence', 'SS2', '1st', 'Core', 'Science'),
('Mathematics', 'MTH221', 'Mathematics - Advanced algebra, calculus, trigonometry, and mathematical analysis for scientific applications', 'SS2', '1st', 'Core', 'Science'),
('Biology', 'BIO221', 'Biology - Advanced study of living organisms, genetics, ecology, and human biology with laboratory work', 'SS2', '1st', 'Core', 'Science'),
('Chemistry', 'CHM221', 'Chemistry - Advanced chemical principles, organic chemistry, and analytical chemistry with practical experiments', 'SS2', '1st', 'Core', 'Science'),
('Physics', 'PHY221', 'Physics - Advanced mechanics, electricity, magnetism, and modern physics with mathematical applications', 'SS2', '1st', 'Core', 'Science'),
('Further Mathematics', 'FMH221', 'Further Mathematics - Complex mathematical concepts, calculus, and advanced problem-solving techniques', 'SS2', '1st', 'Elective', 'Science'),
('Agricultural Science', 'AGR221', 'Agricultural Science - Advanced crop science, animal science, and agricultural technology', 'SS2', '1st', 'Core', 'Science'),
('Economics', 'ECO221', 'Economics - Microeconomics, macroeconomics, and economic theory with Nigerian economic context', 'SS2', '1st', 'Core', 'Science'),
('Civic Education', 'CVE221', 'Civic Education - Advanced citizenship, democracy, and civic engagement in Nigerian society', 'SS2', '1st', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT221', 'Information and Communication Technology - Advanced computer applications, programming, and digital literacy', 'SS2', '1st', 'Core', 'Science'),
('Technical Drawing', 'TDR221', 'Technical Drawing - Engineering drawing, architectural design, and technical communication skills', 'SS2', '1st', 'Core', 'Science'),
('Food & Nutrition', 'FNT221', 'Food & Nutrition - Human nutrition, food science, and dietary management for health', 'SS2', '1st', 'Core', 'Science'),
('English', 'ENG222', 'English Language and Literature', 'SS2', '2nd', 'Core', 'Science'),
('Mathematics', 'MTH222', 'Mathematics', 'SS2', '2nd', 'Core', 'Science'),
('Biology', 'BIO222', 'Biology', 'SS2', '2nd', 'Core', 'Science'),
('Chemistry', 'CHM222', 'Chemistry', 'SS2', '2nd', 'Core', 'Science'),
('Physics', 'PHY222', 'Physics', 'SS2', '2nd', 'Core', 'Science'),
('Further Mathematics', 'FMH222', 'Further Mathematics', 'SS2', '2nd', 'Elective', 'Science'),
('Agricultural Science', 'AGR222', 'Agricultural Science', 'SS2', '2nd', 'Core', 'Science'),
('Economics', 'ECO222', 'Economics', 'SS2', '2nd', 'Core', 'Science'),
('Civic Education', 'CVE222', 'Civic Education', 'SS2', '2nd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT222', 'Information and Communication Technology', 'SS2', '2nd', 'Core', 'Science'),
('English', 'ENG223', 'English Language and Literature', 'SS2', '3rd', 'Core', 'Science'),
('Mathematics', 'MTH223', 'Mathematics', 'SS2', '3rd', 'Core', 'Science'),
('Biology', 'BIO223', 'Biology', 'SS2', '3rd', 'Core', 'Science'),
('Chemistry', 'CHM223', 'Chemistry', 'SS2', '3rd', 'Core', 'Science'),
('Physics', 'PHY223', 'Physics', 'SS2', '3rd', 'Core', 'Science'),
('Further Mathematics', 'FMH223', 'Further Mathematics', 'SS2', '3rd', 'Elective', 'Science'),
('Agricultural Science', 'AGR223', 'Agricultural Science', 'SS2', '3rd', 'Core', 'Science'),
('Economics', 'ECO223', 'Economics', 'SS2', '3rd', 'Core', 'Science'),
('Civic Education', 'CVE223', 'Civic Education', 'SS2', '3rd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT223', 'Information and Communication Technology', 'SS2', '3rd', 'Core', 'Science'),
('English', 'ENG231', 'English Language and Literature', 'SS3', '1st', 'Core', 'Science'),
('Mathematics', 'MTH231', 'Mathematics', 'SS3', '1st', 'Core', 'Science'),
('Biology', 'BIO231', 'Biology', 'SS3', '1st', 'Core', 'Science'),
('Chemistry', 'CHM231', 'Chemistry', 'SS3', '1st', 'Core', 'Science'),
('Physics', 'PHY231', 'Physics', 'SS3', '1st', 'Core', 'Science'),
('Further Mathematics', 'FMH231', 'Further Mathematics', 'SS3', '1st', 'Elective', 'Science'),
('Agricultural Science', 'AGR231', 'Agricultural Science', 'SS3', '1st', 'Core', 'Science'),
('Economics', 'ECO231', 'Economics', 'SS3', '1st', 'Core', 'Science'),
('Civic Education', 'CVE231', 'Civic Education', 'SS3', '1st', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT231', 'Information and Communication Technology', 'SS3', '1st', 'Core', 'Science'),
('English', 'ENG232', 'English Language and Literature', 'SS3', '2nd', 'Core', 'Science'),
('Mathematics', 'MTH232', 'Mathematics', 'SS3', '2nd', 'Core', 'Science'),
('Biology', 'BIO232', 'Biology', 'SS3', '2nd', 'Core', 'Science'),
('Chemistry', 'CHM232', 'Chemistry', 'SS3', '2nd', 'Core', 'Science'),
('Physics', 'PHY232', 'Physics', 'SS3', '2nd', 'Core', 'Science'),
('Further Mathematics', 'FMH232', 'Further Mathematics', 'SS3', '2nd', 'Elective', 'Science'),
('Agricultural Science', 'AGR232', 'Agricultural Science', 'SS3', '2nd', 'Core', 'Science'),
('Economics', 'ECO232', 'Economics', 'SS3', '2nd', 'Core', 'Science'),
('Civic Education', 'CVE232', 'Civic Education', 'SS3', '2nd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT232', 'Information and Communication Technology', 'SS3', '2nd', 'Core', 'Science'),
('English', 'ENG233', 'English Language and Literature', 'SS3', '3rd', 'Core', 'Science'),
('Mathematics', 'MTH233', 'Mathematics', 'SS3', '3rd', 'Core', 'Science'),
('Biology', 'BIO233', 'Biology', 'SS3', '3rd', 'Core', 'Science'),
('Chemistry', 'CHM233', 'Chemistry', 'SS3', '3rd', 'Core', 'Science'),
('Physics', 'PHY233', 'Physics', 'SS3', '3rd', 'Core', 'Science'),
('Further Mathematics', 'FMH233', 'Further Mathematics', 'SS3', '3rd', 'Elective', 'Science'),
('Agricultural Science', 'AGR233', 'Agricultural Science', 'SS3', '3rd', 'Core', 'Science'),
('Economics', 'ECO233', 'Economics', 'SS3', '3rd', 'Core', 'Science'),
('Civic Education', 'CVE233', 'Civic Education', 'SS3', '3rd', 'Core', 'Science'),
('ICT/Computer Studies', 'ICT233', 'Information and Communication Technology', 'SS3', '3rd', 'Core', 'Science'),
('English', 'ENG241', 'English Language and Literature', 'SS1', '1st', 'Core', 'Art'),
('Mathematics', 'MTH241', 'Mathematics', 'SS1', '1st', 'Core', 'Art'),
('Literature in English', 'LIT241', 'Literature in English', 'SS1', '1st', 'Core', 'Art'),
('Government', 'GOV241', 'Government', 'SS1', '1st', 'Core', 'Art'),
('History', 'HIS241', 'History', 'SS1', '1st', 'Core', 'Art'),
('Christian Religious Studies', 'CRS241', 'Christian Religious Studies', 'SS1', '1st', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS241', 'Islamic Religious Studies', 'SS1', '1st', 'Core', 'Art'),
('Economics', 'ECO241', 'Economics', 'SS1', '1st', 'Core', 'Art'),
('Civic Education', 'CVE241', 'Civic Education', 'SS1', '1st', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT241', 'Information and Communication Technology', 'SS1', '1st', 'Core', 'Art'),
('English', 'ENG242', 'English Language and Literature', 'SS1', '2nd', 'Core', 'Art'),
('Mathematics', 'MTH242', 'Mathematics', 'SS1', '2nd', 'Core', 'Art'),
('Literature in English', 'LIT242', 'Literature in English', 'SS1', '2nd', 'Core', 'Art'),
('Government', 'GOV242', 'Government', 'SS1', '2nd', 'Core', 'Art'),
('History', 'HIS242', 'History', 'SS1', '2nd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS242', 'Christian Religious Studies', 'SS1', '2nd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS242', 'Islamic Religious Studies', 'SS1', '2nd', 'Core', 'Art'),
('Economics', 'ECO242', 'Economics', 'SS1', '2nd', 'Core', 'Art'),
('Civic Education', 'CVE242', 'Civic Education', 'SS1', '2nd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT242', 'Information and Communication Technology', 'SS1', '2nd', 'Core', 'Art'),
('English', 'ENG243', 'English Language and Literature', 'SS1', '3rd', 'Core', 'Art'),
('Mathematics', 'MTH243', 'Mathematics', 'SS1', '3rd', 'Core', 'Art'),
('Literature in English', 'LIT243', 'Literature in English', 'SS1', '3rd', 'Core', 'Art'),
('Government', 'GOV243', 'Government', 'SS1', '3rd', 'Core', 'Art'),
('History', 'HIS243', 'History', 'SS1', '3rd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS243', 'Christian Religious Studies', 'SS1', '3rd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS243', 'Islamic Religious Studies', 'SS1', '3rd', 'Core', 'Art'),
('Economics', 'ECO243', 'Economics', 'SS1', '3rd', 'Core', 'Art'),
('Civic Education', 'CVE243', 'Civic Education', 'SS1', '3rd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT243', 'Information and Communication Technology', 'SS1', '3rd', 'Core', 'Art'),
('English', 'ENG251', 'English Language and Literature', 'SS2', '1st', 'Core', 'Art'),
('Mathematics', 'MTH251', 'Mathematics', 'SS2', '1st', 'Core', 'Art'),
('Literature in English', 'LIT251', 'Literature in English', 'SS2', '1st', 'Core', 'Art'),
('Government', 'GOV251', 'Government', 'SS2', '1st', 'Core', 'Art'),
('History', 'HIS251', 'History', 'SS2', '1st', 'Core', 'Art'),
('Christian Religious Studies', 'CRS251', 'Christian Religious Studies', 'SS2', '1st', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS251', 'Islamic Religious Studies', 'SS2', '1st', 'Core', 'Art'),
('Economics', 'ECO251', 'Economics', 'SS2', '1st', 'Core', 'Art'),
('Civic Education', 'CVE251', 'Civic Education', 'SS2', '1st', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT251', 'Information and Communication Technology', 'SS2', '1st', 'Core', 'Art'),
('English', 'ENG252', 'English Language and Literature', 'SS2', '2nd', 'Core', 'Art'),
('Mathematics', 'MTH252', 'Mathematics', 'SS2', '2nd', 'Core', 'Art'),
('Literature in English', 'LIT252', 'Literature in English', 'SS2', '2nd', 'Core', 'Art'),
('Government', 'GOV252', 'Government', 'SS2', '2nd', 'Core', 'Art'),
('History', 'HIS252', 'History', 'SS2', '2nd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS252', 'Christian Religious Studies', 'SS2', '2nd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS252', 'Islamic Religious Studies', 'SS2', '2nd', 'Core', 'Art'),
('Economics', 'ECO252', 'Economics', 'SS2', '2nd', 'Core', 'Art'),
('Civic Education', 'CVE252', 'Civic Education', 'SS2', '2nd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT252', 'Information and Communication Technology', 'SS2', '2nd', 'Core', 'Art'),
('English', 'ENG253', 'English Language and Literature', 'SS2', '3rd', 'Core', 'Art'),
('Mathematics', 'MTH253', 'Mathematics', 'SS2', '3rd', 'Core', 'Art'),
('Literature in English', 'LIT253', 'Literature in English', 'SS2', '3rd', 'Core', 'Art'),
('Government', 'GOV253', 'Government', 'SS2', '3rd', 'Core', 'Art'),
('History', 'HIS253', 'History', 'SS2', '3rd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS253', 'Christian Religious Studies', 'SS2', '3rd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS253', 'Islamic Religious Studies', 'SS2', '3rd', 'Core', 'Art'),
('Economics', 'ECO253', 'Economics', 'SS2', '3rd', 'Core', 'Art'),
('Civic Education', 'CVE253', 'Civic Education', 'SS2', '3rd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT253', 'Information and Communication Technology', 'SS2', '3rd', 'Core', 'Art'),
('English', 'ENG261', 'English Language and Literature', 'SS3', '1st', 'Core', 'Art'),
('Mathematics', 'MTH261', 'Mathematics', 'SS3', '1st', 'Core', 'Art'),
('Literature in English', 'LIT261', 'Literature in English', 'SS3', '1st', 'Core', 'Art'),
('Government', 'GOV261', 'Government', 'SS3', '1st', 'Core', 'Art'),
('History', 'HIS261', 'History', 'SS3', '1st', 'Core', 'Art'),
('Christian Religious Studies', 'CRS261', 'Christian Religious Studies', 'SS3', '1st', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS261', 'Islamic Religious Studies', 'SS3', '1st', 'Core', 'Art'),
('Economics', 'ECO261', 'Economics', 'SS3', '1st', 'Core', 'Art'),
('Civic Education', 'CVE261', 'Civic Education', 'SS3', '1st', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT261', 'Information and Communication Technology', 'SS3', '1st', 'Core', 'Art'),
('English', 'ENG262', 'English Language and Literature', 'SS3', '2nd', 'Core', 'Art'),
('Mathematics', 'MTH262', 'Mathematics', 'SS3', '2nd', 'Core', 'Art'),
('Literature in English', 'LIT262', 'Literature in English', 'SS3', '2nd', 'Core', 'Art'),
('Government', 'GOV262', 'Government', 'SS3', '2nd', 'Core', 'Art'),
('History', 'HIS262', 'History', 'SS3', '2nd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS262', 'Christian Religious Studies', 'SS3', '2nd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS262', 'Islamic Religious Studies', 'SS3', '2nd', 'Core', 'Art'),
('Economics', 'ECO262', 'Economics', 'SS3', '2nd', 'Core', 'Art'),
('Civic Education', 'CVE262', 'Civic Education', 'SS3', '2nd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT262', 'Information and Communication Technology', 'SS3', '2nd', 'Core', 'Art'),
('English', 'ENG263', 'English Language and Literature', 'SS3', '3rd', 'Core', 'Art'),
('Mathematics', 'MTH263', 'Mathematics', 'SS3', '3rd', 'Core', 'Art'),
('Literature in English', 'LIT263', 'Literature in English', 'SS3', '3rd', 'Core', 'Art'),
('Government', 'GOV263', 'Government', 'SS3', '3rd', 'Core', 'Art'),
('History', 'HIS263', 'History', 'SS3', '3rd', 'Core', 'Art'),
('Christian Religious Studies', 'CRS263', 'Christian Religious Studies', 'SS3', '3rd', 'Core', 'Art'),
('Islamic Religious Studies', 'IRS263', 'Islamic Religious Studies', 'SS3', '3rd', 'Core', 'Art'),
('Economics', 'ECO263', 'Economics', 'SS3', '3rd', 'Core', 'Art'),
('Civic Education', 'CVE263', 'Civic Education', 'SS3', '3rd', 'Core', 'Art'),
('ICT/Computer Studies', 'ICT263', 'Information and Communication Technology', 'SS3', '3rd', 'Core', 'Art'),
('English', 'ENG271', 'English Language and Literature', 'SS1', '1st', 'Core', 'Commercial'),
('Mathematics', 'MTH271', 'Mathematics', 'SS1', '1st', 'Core', 'Commercial'),
('Economics', 'ECO271', 'Economics', 'SS1', '1st', 'Core', 'Commercial'),
('Financial Accounting', 'ACC271', 'Financial Accounting', 'SS1', '1st', 'Core', 'Commercial'),
('Commerce', 'COM271', 'Commerce', 'SS1', '1st', 'Core', 'Commercial'),
('Government', 'GOV271', 'Government', 'SS1', '1st', 'Core', 'Commercial'),
('Marketing', 'MKT271', 'Marketing', 'SS1', '1st', 'Core', 'Commercial'),
('Office Practice', 'OFP271', 'Office Practice', 'SS1', '1st', 'Core', 'Commercial'),
('Civic Education', 'CVE271', 'Civic Education', 'SS1', '1st', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT271', 'Information and Communication Technology', 'SS1', '1st', 'Core', 'Commercial'),
('English', 'ENG272', 'English Language and Literature', 'SS1', '2nd', 'Core', 'Commercial'),
('Mathematics', 'MTH272', 'Mathematics', 'SS1', '2nd', 'Core', 'Commercial'),
('Economics', 'ECO272', 'Economics', 'SS1', '2nd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC272', 'Financial Accounting', 'SS1', '2nd', 'Core', 'Commercial'),
('Commerce', 'COM272', 'Commerce', 'SS1', '2nd', 'Core', 'Commercial'),
('Government', 'GOV272', 'Government', 'SS1', '2nd', 'Core', 'Commercial'),
('Marketing', 'MKT272', 'Marketing', 'SS1', '2nd', 'Core', 'Commercial'),
('Office Practice', 'OFP272', 'Office Practice', 'SS1', '2nd', 'Core', 'Commercial'),
('Civic Education', 'CVE272', 'Civic Education', 'SS1', '2nd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT272', 'Information and Communication Technology', 'SS1', '2nd', 'Core', 'Commercial'),
('English', 'ENG273', 'English Language and Literature', 'SS1', '3rd', 'Core', 'Commercial'),
('Mathematics', 'MTH273', 'Mathematics', 'SS1', '3rd', 'Core', 'Commercial'),
('Economics', 'ECO273', 'Economics', 'SS1', '3rd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC273', 'Financial Accounting', 'SS1', '3rd', 'Core', 'Commercial'),
('Commerce', 'COM273', 'Commerce', 'SS1', '3rd', 'Core', 'Commercial'),
('Government', 'GOV273', 'Government', 'SS1', '3rd', 'Core', 'Commercial'),
('Marketing', 'MKT273', 'Marketing', 'SS1', '3rd', 'Core', 'Commercial'),
('Office Practice', 'OFP273', 'Office Practice', 'SS1', '3rd', 'Core', 'Commercial'),
('Civic Education', 'CVE273', 'Civic Education', 'SS1', '3rd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT273', 'Information and Communication Technology', 'SS1', '3rd', 'Core', 'Commercial'),
('English', 'ENG281', 'English Language and Literature', 'SS2', '1st', 'Core', 'Commercial'),
('Mathematics', 'MTH281', 'Mathematics', 'SS2', '1st', 'Core', 'Commercial'),
('Economics', 'ECO281', 'Economics', 'SS2', '1st', 'Core', 'Commercial'),
('Financial Accounting', 'ACC281', 'Financial Accounting', 'SS2', '1st', 'Core', 'Commercial'),
('Commerce', 'COM281', 'Commerce', 'SS2', '1st', 'Core', 'Commercial'),
('Government', 'GOV281', 'Government', 'SS2', '1st', 'Core', 'Commercial'),
('Marketing', 'MKT281', 'Marketing', 'SS2', '1st', 'Core', 'Commercial'),
('Office Practice', 'OFP281', 'Office Practice', 'SS2', '1st', 'Core', 'Commercial'),
('Civic Education', 'CVE281', 'Civic Education', 'SS2', '1st', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT281', 'Information and Communication Technology', 'SS2', '1st', 'Core', 'Commercial'),
('English', 'ENG282', 'English Language and Literature', 'SS2', '2nd', 'Core', 'Commercial'),
('Mathematics', 'MTH282', 'Mathematics', 'SS2', '2nd', 'Core', 'Commercial'),
('Economics', 'ECO282', 'Economics', 'SS2', '2nd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC282', 'Financial Accounting', 'SS2', '2nd', 'Core', 'Commercial'),
('Commerce', 'COM282', 'Commerce', 'SS2', '2nd', 'Core', 'Commercial'),
('Government', 'GOV282', 'Government', 'SS2', '2nd', 'Core', 'Commercial'),
('Marketing', 'MKT282', 'Marketing', 'SS2', '2nd', 'Core', 'Commercial'),
('Office Practice', 'OFP282', 'Office Practice', 'SS2', '2nd', 'Core', 'Commercial'),
('Civic Education', 'CVE282', 'Civic Education', 'SS2', '2nd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT282', 'Information and Communication Technology', 'SS2', '2nd', 'Core', 'Commercial'),
('English', 'ENG283', 'English Language and Literature', 'SS2', '3rd', 'Core', 'Commercial'),
('Mathematics', 'MTH283', 'Mathematics', 'SS2', '3rd', 'Core', 'Commercial'),
('Economics', 'ECO283', 'Economics', 'SS2', '3rd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC283', 'Financial Accounting', 'SS2', '3rd', 'Core', 'Commercial'),
('Commerce', 'COM283', 'Commerce', 'SS2', '3rd', 'Core', 'Commercial'),
('Government', 'GOV283', 'Government', 'SS2', '3rd', 'Core', 'Commercial'),
('Marketing', 'MKT283', 'Marketing', 'SS2', '3rd', 'Core', 'Commercial'),
('Office Practice', 'OFP283', 'Office Practice', 'SS2', '3rd', 'Core', 'Commercial'),
('Civic Education', 'CVE283', 'Civic Education', 'SS2', '3rd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT283', 'Information and Communication Technology', 'SS2', '3rd', 'Core', 'Commercial'),
('English', 'ENG291', 'English Language and Literature', 'SS3', '1st', 'Core', 'Commercial'),
('Mathematics', 'MTH291', 'Mathematics', 'SS3', '1st', 'Core', 'Commercial'),
('Economics', 'ECO291', 'Economics', 'SS3', '1st', 'Core', 'Commercial'),
('Financial Accounting', 'ACC291', 'Financial Accounting', 'SS3', '1st', 'Core', 'Commercial'),
('Commerce', 'COM291', 'Commerce', 'SS3', '1st', 'Core', 'Commercial'),
('Government', 'GOV291', 'Government', 'SS3', '1st', 'Core', 'Commercial'),
('Marketing', 'MKT291', 'Marketing', 'SS3', '1st', 'Core', 'Commercial'),
('Office Practice', 'OFP291', 'Office Practice', 'SS3', '1st', 'Core', 'Commercial'),
('Civic Education', 'CVE291', 'Civic Education', 'SS3', '1st', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT291', 'Information and Communication Technology', 'SS3', '1st', 'Core', 'Commercial'),
('English', 'ENG292', 'English Language and Literature', 'SS3', '2nd', 'Core', 'Commercial'),
('Mathematics', 'MTH292', 'Mathematics', 'SS3', '2nd', 'Core', 'Commercial'),
('Economics', 'ECO292', 'Economics', 'SS3', '2nd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC292', 'Financial Accounting', 'SS3', '2nd', 'Core', 'Commercial'),
('Commerce', 'COM292', 'Commerce', 'SS3', '2nd', 'Core', 'Commercial'),
('Government', 'GOV292', 'Government', 'SS3', '2nd', 'Core', 'Commercial'),
('Marketing', 'MKT292', 'Marketing', 'SS3', '2nd', 'Core', 'Commercial'),
('Office Practice', 'OFP292', 'Office Practice', 'SS3', '2nd', 'Core', 'Commercial'),
('Civic Education', 'CVE292', 'Civic Education', 'SS3', '2nd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT292', 'Information and Communication Technology', 'SS3', '2nd', 'Core', 'Commercial'),
('English', 'ENG293', 'English Language and Literature', 'SS3', '3rd', 'Core', 'Commercial'),
('Mathematics', 'MTH293', 'Mathematics', 'SS3', '3rd', 'Core', 'Commercial'),
('Economics', 'ECO293', 'Economics', 'SS3', '3rd', 'Core', 'Commercial'),
('Financial Accounting', 'ACC293', 'Financial Accounting', 'SS3', '3rd', 'Core', 'Commercial'),
('Commerce', 'COM293', 'Commerce', 'SS3', '3rd', 'Core', 'Commercial'),
('Government', 'GOV293', 'Government', 'SS3', '3rd', 'Core', 'Commercial'),
('Marketing', 'MKT293', 'Marketing', 'SS3', '3rd', 'Core', 'Commercial'),
('Office Practice', 'OFP293', 'Office Practice', 'SS3', '3rd', 'Core', 'Commercial'),
('Civic Education', 'CVE293', 'Civic Education', 'SS3', '3rd', 'Core', 'Commercial'),
('ICT/Computer Studies', 'ICT293', 'Information and Communication Technology', 'SS3', '3rd', 'Core', 'Commercial'),
('Catering Craft Practice', 'CAT411', 'Catering Craft Practice - Professional food preparation, cooking techniques, menu planning, and restaurant management skills', 'SS1', '1st', 'Trade', NULL),
('Garment Making', 'GAR411', 'Garment Making - Fashion design, pattern making, sewing techniques, and textile knowledge for clothing production', 'SS1', '1st', 'Trade', NULL),
('Welding & Fabrication', 'WLF411', 'Welding and Fabrication - Metal joining techniques, fabrication processes, and industrial welding applications', 'SS1', '1st', 'Trade', NULL),
('Electrical Installation', 'ELE411', 'Electrical Installation - Electrical wiring, circuit design, safety practices, and electrical system maintenance', 'SS1', '1st', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB411', 'Plumbing and Pipefitting - Water supply systems, drainage, pipe installation, and plumbing maintenance', 'SS1', '1st', 'Trade', NULL),
('Fisheries', 'FSH411', 'Fisheries - Aquaculture, fish farming, marine biology, and sustainable fishing practices', 'SS1', '1st', 'Trade', NULL),
('Animal Husbandry', 'ANH411', 'Animal Husbandry - Livestock management, animal nutrition, breeding, and veterinary care basics', 'SS1', '1st', 'Trade', NULL),
('Data Processing', 'DPR411', 'Data Processing - Computer applications, database management, and information technology skills', 'SS1', '1st', 'Trade', NULL),
('Tourism', 'TOU411', 'Tourism - Travel industry, hospitality management, cultural tourism, and customer service', 'SS1', '1st', 'Trade', NULL),
('Home Management', 'HOM411', 'Home Management - Family resource management, consumer education, and household administration', 'SS1', '1st', 'Trade', NULL),
('Bookkeeping', 'BKK411', 'Bookkeeping - Financial record keeping, accounting principles, and business documentation', 'SS1', '1st', 'Trade', NULL),
('Auto Mechanics', 'AUT411', 'Auto Mechanics - Vehicle maintenance, engine repair, and automotive technology', 'SS1', '1st', 'Trade', NULL),
('Building Construction', 'BDG411', 'Building Construction - Construction techniques, building materials, and architectural drawing', 'SS1', '1st', 'Trade', NULL),
('Printing Technology', 'PRT411', 'Printing Technology - Graphic design, printing processes, and digital media production', 'SS1', '1st', 'Trade', NULL),
('Photography', 'PHT411', 'Photography - Digital photography, photo editing, and visual communication', 'SS1', '1st', 'Trade', NULL),
('Catering Craft Practice', 'CAT412', 'Catering Craft Practice', 'SS1', '2nd', 'Trade', NULL),
('Garment Making', 'GAR412', 'Garment Making', 'SS1', '2nd', 'Trade', NULL),
('Welding & Fabrication', 'WLF412', 'Welding and Fabrication', 'SS1', '2nd', 'Trade', NULL),
('Electrical Installation', 'ELE412', 'Electrical Installation', 'SS1', '2nd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB412', 'Plumbing and Pipefitting', 'SS1', '2nd', 'Trade', NULL),
('Fisheries', 'FSH412', 'Fisheries', 'SS1', '2nd', 'Trade', NULL),
('Animal Husbandry', 'ANH412', 'Animal Husbandry', 'SS1', '2nd', 'Trade', NULL),
('Data Processing', 'DPR412', 'Data Processing', 'SS1', '2nd', 'Trade', NULL),
('Tourism', 'TOU412', 'Tourism', 'SS1', '2nd', 'Trade', NULL),
('Home Management', 'HOM412', 'Home Management', 'SS1', '2nd', 'Trade', NULL),
('Catering Craft Practice', 'CAT413', 'Catering Craft Practice', 'SS1', '3rd', 'Trade', NULL),
('Garment Making', 'GAR413', 'Garment Making', 'SS1', '3rd', 'Trade', NULL),
('Welding & Fabrication', 'WLF413', 'Welding and Fabrication', 'SS1', '3rd', 'Trade', NULL),
('Electrical Installation', 'ELE413', 'Electrical Installation', 'SS1', '3rd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB413', 'Plumbing and Pipefitting', 'SS1', '3rd', 'Trade', NULL),
('Fisheries', 'FSH413', 'Fisheries', 'SS1', '3rd', 'Trade', NULL),
('Animal Husbandry', 'ANH413', 'Animal Husbandry', 'SS1', '3rd', 'Trade', NULL),
('Data Processing', 'DPR413', 'Data Processing', 'SS1', '3rd', 'Trade', NULL),
('Tourism', 'TOU413', 'Tourism', 'SS1', '3rd', 'Trade', NULL),
('Home Management', 'HOM413', 'Home Management', 'SS1', '3rd', 'Trade', NULL),
('Catering Craft Practice', 'CAT421', 'Catering Craft Practice', 'SS2', '1st', 'Trade', NULL),
('Garment Making', 'GAR421', 'Garment Making', 'SS2', '1st', 'Trade', NULL),
('Welding & Fabrication', 'WLF421', 'Welding and Fabrication', 'SS2', '1st', 'Trade', NULL),
('Electrical Installation', 'ELE421', 'Electrical Installation', 'SS2', '1st', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB421', 'Plumbing and Pipefitting', 'SS2', '1st', 'Trade', NULL),
('Fisheries', 'FSH421', 'Fisheries', 'SS2', '1st', 'Trade', NULL),
('Animal Husbandry', 'ANH421', 'Animal Husbandry', 'SS2', '1st', 'Trade', NULL),
('Data Processing', 'DPR421', 'Data Processing', 'SS2', '1st', 'Trade', NULL),
('Tourism', 'TOU421', 'Tourism', 'SS2', '1st', 'Trade', NULL),
('Home Management', 'HOM421', 'Home Management', 'SS2', '1st', 'Trade', NULL),
('Catering Craft Practice', 'CAT422', 'Catering Craft Practice', 'SS2', '2nd', 'Trade', NULL),
('Garment Making', 'GAR422', 'Garment Making', 'SS2', '2nd', 'Trade', NULL),
('Welding & Fabrication', 'WLF422', 'Welding and Fabrication', 'SS2', '2nd', 'Trade', NULL),
('Electrical Installation', 'ELE422', 'Electrical Installation', 'SS2', '2nd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB422', 'Plumbing and Pipefitting', 'SS2', '2nd', 'Trade', NULL),
('Fisheries', 'FSH422', 'Fisheries', 'SS2', '2nd', 'Trade', NULL),
('Animal Husbandry', 'ANH422', 'Animal Husbandry', 'SS2', '2nd', 'Trade', NULL),
('Data Processing', 'DPR422', 'Data Processing', 'SS2', '2nd', 'Trade', NULL),
('Tourism', 'TOU422', 'Tourism', 'SS2', '2nd', 'Trade', NULL),
('Home Management', 'HOM422', 'Home Management', 'SS2', '2nd', 'Trade', NULL),
('Catering Craft Practice', 'CAT423', 'Catering Craft Practice', 'SS2', '3rd', 'Trade', NULL),
('Garment Making', 'GAR423', 'Garment Making', 'SS2', '3rd', 'Trade', NULL),
('Welding & Fabrication', 'WLF423', 'Welding and Fabrication', 'SS2', '3rd', 'Trade', NULL),
('Electrical Installation', 'ELE423', 'Electrical Installation', 'SS2', '3rd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB423', 'Plumbing and Pipefitting', 'SS2', '3rd', 'Trade', NULL),
('Fisheries', 'FSH423', 'Fisheries', 'SS2', '3rd', 'Trade', NULL),
('Animal Husbandry', 'ANH423', 'Animal Husbandry', 'SS2', '3rd', 'Trade', NULL),
('Data Processing', 'DPR423', 'Data Processing', 'SS2', '3rd', 'Trade', NULL),
('Tourism', 'TOU423', 'Tourism', 'SS2', '3rd', 'Trade', NULL),
('Home Management', 'HOM423', 'Home Management', 'SS2', '3rd', 'Trade', NULL),
('Catering Craft Practice', 'CAT431', 'Catering Craft Practice', 'SS3', '1st', 'Trade', NULL),
('Garment Making', 'GAR431', 'Garment Making', 'SS3', '1st', 'Trade', NULL),
('Welding & Fabrication', 'WLF431', 'Welding and Fabrication', 'SS3', '1st', 'Trade', NULL),
('Electrical Installation', 'ELE431', 'Electrical Installation', 'SS3', '1st', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB431', 'Plumbing and Pipefitting', 'SS3', '1st', 'Trade', NULL),
('Fisheries', 'FSH431', 'Fisheries', 'SS3', '1st', 'Trade', NULL),
('Animal Husbandry', 'ANH431', 'Animal Husbandry', 'SS3', '1st', 'Trade', NULL),
('Data Processing', 'DPR431', 'Data Processing', 'SS3', '1st', 'Trade', NULL),
('Tourism', 'TOU431', 'Tourism', 'SS3', '1st', 'Trade', NULL),
('Home Management', 'HOM431', 'Home Management', 'SS3', '1st', 'Trade', NULL),
('Catering Craft Practice', 'CAT432', 'Catering Craft Practice', 'SS3', '2nd', 'Trade', NULL),
('Garment Making', 'GAR432', 'Garment Making', 'SS3', '2nd', 'Trade', NULL),
('Welding & Fabrication', 'WLF432', 'Welding and Fabrication', 'SS3', '2nd', 'Trade', NULL),
('Electrical Installation', 'ELE432', 'Electrical Installation', 'SS3', '2nd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB432', 'Plumbing and Pipefitting', 'SS3', '2nd', 'Trade', NULL),
('Fisheries', 'FSH432', 'Fisheries', 'SS3', '2nd', 'Trade', NULL),
('Animal Husbandry', 'ANH432', 'Animal Husbandry', 'SS3', '2nd', 'Trade', NULL),
('Data Processing', 'DPR432', 'Data Processing', 'SS3', '2nd', 'Trade', NULL),
('Tourism', 'TOU432', 'Tourism', 'SS3', '2nd', 'Trade', NULL),
('Home Management', 'HOM432', 'Home Management', 'SS3', '2nd', 'Trade', NULL),
('Catering Craft Practice', 'CAT433', 'Catering Craft Practice', 'SS3', '3rd', 'Trade', NULL),
('Garment Making', 'GAR433', 'Garment Making', 'SS3', '3rd', 'Trade', NULL),
('Welding & Fabrication', 'WLF433', 'Welding and Fabrication', 'SS3', '3rd', 'Trade', NULL),
('Electrical Installation', 'ELE433', 'Electrical Installation', 'SS3', '3rd', 'Trade', NULL),
('Plumbing & Pipefitting', 'PLB433', 'Plumbing and Pipefitting', 'SS3', '3rd', 'Trade', NULL),
('Fisheries', 'FSH433', 'Fisheries', 'SS3', '3rd', 'Trade', NULL),
('Animal Husbandry', 'ANH433', 'Animal Husbandry', 'SS3', '3rd', 'Trade', NULL),
('Data Processing', 'DPR433', 'Data Processing', 'SS3', '3rd', 'Trade', NULL),
('Tourism', 'TOU433', 'Tourism', 'SS3', '3rd', 'Trade', NULL),
('Home Management', 'HOM433', 'Home Management', 'SS3', '3rd', 'Trade', NULL)

on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  class_level = excluded.class_level,
  term = excluded.term,
  category = excluded.category,
  stream = excluded.stream,
  updated_at = now();

COMMIT;

-- Set appropriate subject types based on course names
UPDATE public.new_courses SET subject_type = 'Language' WHERE name ILIKE '%English%' OR name ILIKE '%Literacy%';
UPDATE public.new_courses SET subject_type = 'Mathematics' WHERE name ILIKE '%Mathematics%' OR name ILIKE '%Math%' OR name ILIKE '%Numeracy%';
UPDATE public.new_courses SET subject_type = 'Science' WHERE name ILIKE '%Science%' OR name ILIKE '%Technology%' OR name ILIKE '%Biology%' OR name ILIKE '%Chemistry%' OR name ILIKE '%Physics%';
UPDATE public.new_courses SET subject_type = 'Social Studies' WHERE name ILIKE '%Social%' OR name ILIKE '%Civic%' OR name ILIKE '%Studies%';
UPDATE public.new_courses SET subject_type = 'Arts' WHERE name ILIKE '%Art%' OR name ILIKE '%Creative%';
UPDATE public.new_courses SET subject_type = 'Physical Education' WHERE name ILIKE '%Physical%' OR name ILIKE '%Health%' OR name ILIKE '%PHE%';
UPDATE public.new_courses SET subject_type = 'Agriculture' WHERE name ILIKE '%Agricultural%' OR name ILIKE '%Agriculture%';
UPDATE public.new_courses SET subject_type = 'Trade' WHERE category = 'Trade';
UPDATE public.new_courses SET subject_type = 'Reasoning' WHERE name ILIKE '%Reasoning%';

UPDATE public.new_courses SET stream = NULL WHERE stream = NULL AND class_level IN ('KG1','KG2','PRI1','PRI2','PRI3','PRI4','PRI5','PRI6','JSS1','JSS2','JSS3');

-- Rename the new table to replace the old one
ALTER TABLE public.new_courses RENAME TO courses;